version: "3.9"

services:
  pizzahouse_db:
    image: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: pizzahouse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    container_name: pizzahouse_db_cont
    ports:
      - "15432:5432"
    volumes:
      - pizzahouse_db_vol:/var/lib/postgres/data

volumes:
  pizzahouse_db_vol:
